### ISSUE TITLE
Build breakage on non-x86 due to -malign-double

### ISSUE THREAD

**Issue by afaerber** [angr/vex#14]
pyvex builds on ppc64(le), aarch64 and possibly others break because `-malign-double` is not a valid flag on all architectures.

https://github.com/angr/vex/blob/b08ff6739a29b0ca3a8218ec7516513dca978ce9/Makefile-gcc#L43-L47

Introduced in b773fc63421f409f60552c632a0cdff0cc737926, not in upstream Valgrind.

**Comment by rhelmot** [comment]
I have some extremely bad news if you’re trying to get angr to run on non intel platforms. This is absolutely not the last problem you’ll run into. LibVEX was theoretically written to be architecture independent, but this is a complete lie and we have had to twist its arms in horrifying, disgusting ways in order to even be able to lift for arches on x86_64, and then even harder on i386. I once got it working on 32 bit armel, but I can’t remember if I merged all the necessary hacks. Forget a big endian platform, that’ll be >1000 lines of edits in vex probably. 

For this reason, I can’t help you if you want to go down this path. Plus I don’t have access to the machines to test this...

Submit a pull request if you would like this fixed. Maybe I’m wrong about how hard it is :)

**Comment by afaerber** [comment]
For now I've limited the architectures we build pyvex for to 32-bit and 64-bit Intel:
https://build.opensuse.org/package/view_file/devel:languages:python/python-pyvex/python-pyvex.spec?expand=1

For comparison here's the list of architectures we build valgrind for, which includes three Big Endian targets:
https://build.opensuse.org/package/view_file/devel:tools/valgrind/valgrind.spec?expand=1

**Comment by rhelmot** [comment]
Right - I don’t think I was clear enough: libvex works fine when the host
and guest architectures are the same, but when you’re doing
cross-architecture stuff, that is, everything you ever do with angr,
everything falls apart.

**Comment by rhelmot** [comment]
I finally figured out how to do this! No guarantees that anything will work correctly, but it should at least build now :)
