### ISSUE TITLE
Plans to support VEX JIT like Valgring in `vg_from_ucode.c`

### ISSUE THREAD

**Issue by trustednstaller** [angr/vex#69]
### Question

Valgrind through VEX-IR supports JIT'ing the IR back to native machine instructions (`vg_from_ucode.c`, `emitUInstr`, etc.) - does angr have plans to provide this support through their VEX fork? It would be really handy to be able to JIT existing VEX-IR back to the native machine instructions.

**Comment by rhelmot** [comment]
We've never had a use case for it and I don't think any of us know much about that part of VEX. Would the patches be pretty simple?

If I'm recalling correctly, I talked to the valgrind people once and they said not to bother with the cross-JIT (mismatched host and guest) because it had never been tested, and that's almost our entire use-case for pyvex, so my guess to the posed question would be "no"...

**Comment by ltfish** [comment]
My two cents: Patching in cross-arch JIT support to libvex will be very engineering heavy (dealing with all sorts of architecture-specific helper functions). Our solution so far has been Qemu-based emulation (unicorn-engine integration) and PCode-based emulation (see Icicle, for example).
